---
- name: deploy zookeeper cluster
  hosts: zookeeper
  become: True
  roles:
    - zookeeper
- name: deploy kafka cluster
  hosts: kafka
  become: True
  roles:
    - kafka
- name: deploy kafka connect cluster
  hosts: kafka_connect
  become: True
  roles:
    - kafka-connect