---
- name: KAFKA - ensure kafka_broker_id var
  fail:
    msg: "kafka_broker_id is required"
  when: "kafka_broker_id is undefined"
- name: KAFKA - ensure dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: '0755'
  with_items: 
    - "{{ kafka_broker_log_dirs }}"
- name: KAFKA - copy config files
  template:
    src: "{{ item }}"
    dest: "{{ kafka_home }}/config/{{ item[:-3] }}"
    owner: kafka
    group: kafka
    mode: '0644'
  with_items: 
    - server.properties.j2
  notify: restart kafka broker
- name: KAFKA - kafka broker service
  template:
    src: kafka-broker.service.j2
    dest: /etc/systemd/system/kafka-broker.service
    owner: root
    group: root
    mode: 0644
  notify: restart kafka broker
