- name: KAFKA COMMON - create kafka group
  group:
    name: kafka
    system: yes
    state: present
- name: KAFKA COMMON - create kafka user
  user:
    name: kafka
    groups: kafka
    append: yes
    system: yes
    state: present
- name: KAFKA COMMON - ensure dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: '0755'
  with_items: 
    - /var/log/kafka
- name: KAFKA COMMON - kafka path stat
  stat:
    path: /opt/kafka_{{ scala_version }}-{{ kafka_version }}
  register: kafka_path_stat_result
- block:
  - name: KAFKA COMMON - download kafka
    get_url:
      url: http://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
      dest: /tmp
  - name: KAFKA COMMON - unarchive kafka
    unarchive:
      src: /tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
      dest: /opt
      remote_src: yes
      owner: kafka
      group: kafka
  when: not kafka_path_stat_result.stat.exists
- name: KAFKA COMMON - link kafka home
  file:
    src: /opt/kafka_{{ scala_version }}-{{ kafka_version }}
    dest: "{{ kafka_home }}"
    owner: kafka
    group: kafka
    state: link
